/*
 * Payment API
 *
 * Demo code
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PaymentAttributes struct {

	Amount string `json:"amount,omitempty"`

	BeneficiaryParty *PaymentAttributesBeneficiaryParty `json:"beneficiary_party,omitempty"`

	ChargesInformation *PaymentAttributesChargesInformation `json:"charges_information,omitempty"`

	Currency string `json:"currency,omitempty"`

	DebtorParty *PaymentAttributesDebtorParty `json:"debtor_party,omitempty"`

	EndToEndReference string `json:"end_to_end_reference,omitempty"`

	Fx *PaymentAttributesFx `json:"fx,omitempty"`

	NumericReference string `json:"numeric_reference,omitempty"`

	PaymentId string `json:"payment_id,omitempty"`

	PaymentPurpose string `json:"payment_purpose,omitempty"`

	PaymentScheme string `json:"payment_scheme,omitempty"`

	PaymentType string `json:"payment_type,omitempty"`

	ProcessingDate string `json:"processing_date,omitempty"`

	Reference string `json:"reference,omitempty"`

	SchemePaymentSubType string `json:"scheme_payment_sub_type,omitempty"`

	SchemePaymentType string `json:"scheme_payment_type,omitempty"`

	SponsorParty *PaymentAttributesSponsorParty `json:"sponsor_party,omitempty"`
}
