/*
 * Payment API
 *
 * Demo code
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PaymentAttributesChargesInformation struct {

	BearerCode string `json:"bearer_code,omitempty"`

	SenderCharges []PaymentAttributesChargesInformationSenderCharges `json:"sender_charges,omitempty"`

	ReceiverChargesAmount string `json:"receiver_charges_amount,omitempty"`

	ReceiverChargesCurrency string `json:"receiver_charges_currency,omitempty"`
}
