/*
 * Payment API
 *
 * Demo code
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PaymentAttributesSponsorParty struct {

	AccountNumber string `json:"account_number,omitempty"`

	BankId string `json:"bank_id,omitempty"`

	BankIdCode string `json:"bank_id_code,omitempty"`
}
