/*
 * Payment API
 *
 * Demo code
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PaymentAttributesDebtorParty struct {

	AccountName string `json:"account_name,omitempty"`

	AccountNumber string `json:"account_number,omitempty"`

	AccountNumberCode string `json:"account_number_code,omitempty"`

	Address string `json:"address,omitempty"`

	BankId string `json:"bank_id,omitempty"`

	BankIdCode string `json:"bank_id_code,omitempty"`

	Name string `json:"name,omitempty"`
}
