/*
 * Payment API
 *
 * Demo code
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PaymentAttributesChargesInformationSenderCharges struct {

	Amount string `json:"amount,omitempty"`

	Currency string `json:"currency,omitempty"`
}
